services:
  node-app:
    container_name: webhotreloade
    image: mahmoudadisi1/project-2-node-app
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    env_file:
      - ./.env 
    depends_on:
      - mongo
      - redis
    networks:
      my-network:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
        - mongo
    networks:
      my-network:
  redis:
    image: redis
    networks:
      my-network:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - node-app
    networks:
      my-network:
volumes:
  mongo-db:
networks:
      my-network:
    